# Get all users
GET {{protocol}}://{{host}}:{{port}}/ping HTTP/1.1

###

# Get all users
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/users HTTP/1.1

###

# Add new useer
POST {{protocol}}://{{host}}:{{port}}/api/{{version}}/users/register HTTP/1.1
Content-Type: application/json

{
	"id" : 0,
	"firstname" : "Dev 0",
	"lastname": "Test",
	"fullname": "Dev 0 Test",
	"email": "dev0@test.com",
	"profilePic": "http://test.com/dev0/profile.jpg",
	"createAt": "2017-08-30T13:35:00Z",
	"isActive": true
}